# -*- coding: utf-8 -*-
"""AlgorithmicThinking&DataStructures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqupOMBsAZBmeTYqrv_D5oP8ist87j73
"""

def capitalize_words(input_string):
    words = input_string.split()
    capitalized_words = [word.capitalize() for word in words]
    capitalized_string = ' '.join(capitalized_words)
    return capitalized_string

#test case
print(capitalize_words("hello world"))